plugins { id 'com.android.application' }

android {
    namespace 'com.livetgtv.nativeapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.livetgtv.nativeapp'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    buildTypes { release { minifyEnabled false } }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.6.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.6.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.6.1'
    implementation 'androidx.media3:media3-ui:1.6.1'
}
